In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: skimpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.0.6)
Requirement already satisfied: click<9.0.0,>=8.1.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (8.1.3)
Requirement already satisfied: typeguard<3.0.0,>=2.12.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (2.13.3)
Requirement already satisfied: Pygments<3.0.0,>=2.10.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (2.12.0)
Requirement already satisfied: pandas<2.0.0,>=1.3.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (1.3.2)
Requirement already satisfied: rich<13.0,>=10.9 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (12.4.4)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (1.23.0)
Requirement already satisfied: black<23.0.0,>=22.3.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (22.6.0)
Requirement already satisfied: jupyter<2.0.0,>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (1.0.0)
Requirement already satisfied: ipykernel<7.0.0,>=6.7.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from skimpy) (6.15.0)
Requirement already satisfied: pathspec>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from black<23.0.0,>=22.3.0->skimpy) (0.9.0)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from black<23.0.0,>=22.3.0->skimpy) (4.2.0)
Requirement already satisfied: tomli>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from black<23.0.0,>=22.3.0->skimpy) (2.0.1)
Requirement already satisfied: platformdirs>=2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from black<23.0.0,>=22.3.0->skimpy) (2.5.2)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from black<23.0.0,>=22.3.0->skimpy) (0.4.3)
Requirement already satisfied: jupyter-client>=6.1.12 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (7.3.4)
Requirement already satisfied: debugpy>=1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (1.6.0)
Requirement already satisfied: nest-asyncio in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (1.5.5)
Requirement already satisfied: pyzmq>=17 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (23.2.0)
Requirement already satisfied: ipython>=7.23.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (8.4.0)
Requirement already satisfied: traitlets>=5.1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.3.0)
Requirement already satisfied: tornado>=6.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (6.1)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (21.3)
Requirement already satisfied: appnope in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (0.1.3)
Requirement already satisfied: psutil in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipykernel<7.0.0,>=6.7.0->skimpy) (0.1.3)
Requirement already satisfied: ipywidgets in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (7.7.1)
Requirement already satisfied: qtconsole in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (5.3.1)
Requirement already satisfied: notebook in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (6.4.12)
Requirement already satisfied: nbconvert in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (6.5.0)
Requirement already satisfied: jupyter-console in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter<2.0.0,>=1.0.0->skimpy) (6.4.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas<2.0.0,>=1.3.2->skimpy) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pandas<2.0.0,>=1.3.2->skimpy) (2021.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from rich<13.0,>=10.9->skimpy) (0.9.1)
Requirement already satisfied: setuptools>=18.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (56.0.0)
Requirement already satisfied: backcall in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (3.0.29)
Requirement already satisfied: jedi>=0.16 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.18.1)
Requirement already satisfied: pickleshare in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.7.5)
Requirement already satisfied: stack-data in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.3.0)
Requirement already satisfied: pexpect>4.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (4.8.0)
Requirement already satisfied: decorator in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (5.1.1)
Requirement already satisfied: entrypoints in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.7.0->skimpy) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jupyter-client>=6.1.12->ipykernel<7.0.0,>=6.7.0->skimpy) (4.10.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.3.2->skimpy) (1.16.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (1.1.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->skimpy) (3.6.1)
Requirement already satisfied: nbclient>=0.5.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.6.5)
Requirement already satisfied: defusedxml in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.7.1)
Requirement already satisfied: nbformat>=5.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (5.4.0)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (4.11.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.8.4)
Requirement already satisfied: bleach in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (5.0.1)
Requirement already satisfied: jinja2>=3.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (2.1.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (1.5.0)
Requirement already satisfied: tinycss2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (1.1.1)
Requirement already satisfied: jupyterlab-pygments in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.2.2)
Requirement already satisfied: argon2-cffi in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (21.3.0)
Requirement already satisfied: prometheus-client in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.14.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from notebook->jupyter<2.0.0,>=1.0.0->skimpy) (0.15.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from packaging->ipykernel<7.0.0,>=6.7.0->skimpy) (3.0.9)
Requirement already satisfied: qtpy>=2.0.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from qtconsole->jupyter<2.0.0,>=1.0.0->skimpy) (2.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.8.3)
Requirement already satisfied: jsonschema>=2.6 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (4.6.1)
Requirement already satisfied: fastjsonschema in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (2.15.3)
Requirement already satisfied: ptyprocess>=0.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.7.0)
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.5)
Requirement already satisfied: argon2-cffi-bindings in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (21.2.0)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from beautifulsoup4->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (2.3.2.post1)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from bleach->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.5.1)
Requirement already satisfied: asttokens in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from stack-data->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (2.0.5)
Requirement already satisfied: executing in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from stack-data->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.8.3)
Requirement already satisfied: pure-eval in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from stack-data->ipython>=7.23.1->ipykernel<7.0.0,>=6.7.0->skimpy) (0.2.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter<2.0.0,>=1.0.0->skimpy) (21.4.0)
Requirement already satisfied: cffi>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from argon2-cffi-bindings->argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (1.15.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->skimpy) (2.21)
WARNING: There was an error checking the latest version of pip.

In [13]:
# !pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 1.0 MB/s eta 0:00:00a 0:00:01
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10
WARNING: There was an error checking the latest version of pip.

In [222]:
path = "/Users/saraali/Documents/misk-DSI/gov_banking_eda/data/" 
df_2018 = pd.read_csv(path+'social-development-bank-loans-for-2018.csv')
df_2019 = pd.read_csv(path+'social-development-bank-loans-for-2019.csv')
df_2020 = pd.read_excel(path+'social-development-bank-loans-for-2020..xlsx')
df_2021 = pd.read_csv(path+'social_devlopment_bank_loans_for_2021.csv')
df_2022 = pd.read_csv(path+'social_devlopment_bank_loans_for_2022.csv')

df_2018['السنة'] = 2018
df_2019['السنة'] = 2019
df_2020['السنة'] = 2020
df_2021['السنة'] = 2021
df_2022['السنة'] = 2022


df_2021['قرض ادخاري'] = "غير معروف"
df_2022['القيمة'] = "غير معروف"

In [223]:
df_2018.head()

,ID,فرع البنك,نوع التمويل,تصنيف التمويل,قطاع العميل,قيمة التمويل,قيمة القسط,تاريخ الصرف,جنس العميل,عمرالعميل,الحالة الاجتماعية,احتياجات خاصة,عدد افراد الاسرة,قرض ادخاري,قيمة الدخل,السنة
0,1.0,الإحساء,إجتماعي,أسرة,موظف حكومي,60000.0,>= 1000,2018/01,MALE,>= 40,متزوج,لا,>= 02,لا,>= 7500,2018
1,2.0,الإحساء,مشروع,ناشيء,متقاعد حكومي,122000.0,>= 1000,2018/01,MALE,>= 40,متزوج,لا,< 02,لا,< 5000,2018
2,3.0,الإحساء,إجتماعي,أسرة,متقاعد حكومي,60000.0,>= 1000,2018/01,MALE,>= 40,متزوج,لا,>= 05,لا,< 5000,2018
3,4.0,الإحساء,إجتماعي,زواج,موظف حكومي,48000.0,< 1000,2018/01,MALE,>= 30,متزوج,لا,>= 02,لا,>= 5000,2018
4,5.0,الإحساء,مشروع,عربات البيع,NaN,150000.0,>= 1000,2018/01,MALE,>= 30,متزوج,لا,< 02,لا,< 5000,2018

In [224]:
df_2019.head()

,ID,فرع البنك,نوع التمويل,تصنيف التمويل,قطاع العميل,قيمة التمويل,قيمة القسط,تاريخ الصرف,جنس العميل,عمرالعميل,الحالة الاجتماعية,احتياجات خاصة,عدد افراد الاسرة,قرض ادخاري,قيمة الدخل,السنة
0,1.0,تبوك,إجتماعي,أسرة,موظف حكومي,60000.0,>= 1000,2019/02,MALE,>= 30,متزوج,لا,>= 05,لا,< 5000,2019
1,2.0,حائل,مشروع,حل,NaN,160000.0,>= 1000,2019/01,MALE,< 30,أعزب,لا,< 02,لا,< 5000,2019
2,3.0,تبوك,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2019/02,MALE,< 30,متزوج,لا,>= 02,لا,>= 7500,2019
3,4.0,المدينة,إجتماعي,زواج,موظف شركة حكومية,60000.0,< 1000,2019/03,MALE,< 30,متزوج,لا,>= 10,لا,>= 5000,2019
4,5.0,المدينة,إجتماعي,أسرة,موظف قطاع خاص,60000.0,>= 1000,2019/02,FEMALE,>= 30,مطلق,لا,>= 02,لا,>= 10000,2019

In [225]:
df_2020.head()

,ID,فرع البنك,نوع التمويل,تصنيف التمويل,قطاع العميل,قيمة التمويل,قيمة القسط,تاريخ الصرف,جنس العميل,عمرالعميل,الحالة الاجتماعية,احتياجات خاصة,عدد افراد الاسرة,قرض ادخاري,قيمة الدخل,السنة
0,6,الرس,تمويل الافراد,أسرة,غير محدد,60000,>= 1000,2020/03,أنثى,>= 30,مطلق,لا,>= 02,نعم,< 5000,2020
1,7,الرياض,تمويل الافراد,زواج,موظف حكومي,60000,>= 1000,2020/03,ذكر,< 30,متزوج,لا,>= 02,لا,>= 7500,2020
2,47,الرياض,تمويل الافراد,زواج,غير محدد,60000,>= 1000,2020/01,ذكر,< 30,متزوج,لا,>= 02,لا,< 5000,2020
3,48,مكة,تمويل الافراد,زواج,غير محدد,60000,>= 1000,2020/03,ذكر,< 30,متزوج,لا,>= 02,نعم,< 5000,2020
4,49,الطائف,تمويل الافراد,زواج,موظف حكومي,60000,>= 1000,2020/03,ذكر,< 30,متزوج,لا,>= 02,لا,>= 7500,2020

In [226]:
df_2021.head()

,ID,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمرالعميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد افراد الاسرة,قيمة الدخل,السنة,قرض ادخاري
0,1,حائل,مشروع,قرض مشروع ناشيء,غير معرف,30000.0,<1000,2021/1,ذكر,>= 30,متزوج,سليم,غير معروف,<5000,2021,غير معروف
1,2,الطائف,نقل,قرض سيارة أجرة,غير معرف,54694.0,<1000,2021/1,ذكر,>= 30,متزوج,سليم,>= 02,<5000,2021,غير معروف
2,8,الرياض,مشروع,قرض التميز,قطاع خاص,1585000.0,>=1000,2021/1,أنثى,>= 40,أعزب,سليم,< 02,>=10000,2021,غير معروف
3,12,مكه المكرمه,نقل,قرض أجرة خاصة,قطاع حكومي,97230.0,>=1000,2021/1,ذكر,>= 40,متزوج,سليم,< 02,<5000,2021,غير معروف
4,13,جازان,نقل,قرض أجرة خاصة,قطاع حكومي,97230.0,>=1000,2021/1,ذكر,< 30,أعزب,سليم,< 02,<5000,2021,غير معروف

In [227]:
df_2022.head()

,ID,المدينة,التصنيف,االمنتج,قطاع_العميل,مبلغ_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,ألحاله_الإجتماعية,إحتياجات_خاصة,عدد_أفراد_الأسره,زود_الإدخاري,القيمة,السنة
0,1,بنك التنمية الإجتماعية فرع المجمعة,مشروع,قرض التميز,قطاع خاص,2877000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,غير معروف,2022
1,2,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض مشروع حل,قطاع خاص,281000.0,>= 1000,2022-03,انثى,>= 30,متزوج,سليم,< 02,0,غير معروف,2022
2,3,بنك التنمية الإجتماعية فرع جدة,مشروع,قرض التميز,قطاع خاص,2218980.0,>= 1000,2022-01,ذكر,>= 30,متزوج,سليم,< 02,0,غير معروف,2022
3,4,بنك التنمية الإجتماعية بالمدينة المنورة,مشروع,قرض التقنيات الناشئة,قطاع خاص,260000.0,>= 1000,2022-01,انثى,>= 30,متزوج,سليم,< 02,0,غير معروف,2022
4,5,بنك التنمية الإجتماعية فرع الرياض,مشروع,قرض التقنيات الناشئة,قطاع خاص,220000.0,>= 1000,2022-03,ذكر,>= 30,متزوج,سليم,< 02,0,غير معروف,2022

In [232]:
df_2021 = df_2021[['ID', 'المدينة', 'التصنيف', 'االمنتج', 'قطاع_العميل', 'مبلغ_التمويل','قيمة_القسط', 'تاريخ_الصرف', 'جنس_العميل', 'عمرالعميل',
                    'ألحاله_الإجتماعية','إحتياجات_خاصة','عدد افراد الاسرة','قرض ادخاري','قيمة الدخل','السنة']]

In [233]:
dfs = [df_2018, df_2019, df_2020, df_2021 ,df_2022]
names = 'ID	المدينة	نوع_التمويل	المنتج	قطاع_العميل	قيمة_التمويل	قيمة_القسط	تاريخ_الصرف	جنس_العميل	عمر_العميل	الحالة_الاجتماعية	احتياجات_خاصة	عدد_افراد_الاسرة	قرض_ادخاري	قيمة_الدخل	السنة'.split()

for i in dfs:
    i.columns = names

In [234]:
data = pd.concat([df_2018, df_2019, df_2020, df_2021, df_2022], ignore_index = True)
data.head(20)

,ID,المدينة,نوع_التمويل,المنتج,قطاع_العميل,قيمة_التمويل,قيمة_القسط,تاريخ_الصرف,جنس_العميل,عمر_العميل,الحالة_الاجتماعية,احتياجات_خاصة,عدد_افراد_الاسرة,قرض_ادخاري,قيمة_الدخل,السنة
0,1.0,الإحساء,إجتماعي,أسرة,موظف حكومي,60000.0,>= 1000,2018/01,MALE,>= 40,متزوج,لا,>= 02,لا,>= 7500,2018
1,2.0,الإحساء,مشروع,ناشيء,متقاعد حكومي,122000.0,>= 1000,2018/01,MALE,>= 40,متزوج,لا,< 02,لا,< 5000,2018
2,3.0,الإحساء,إجتماعي,أسرة,متقاعد حكومي,60000.0,>= 1000,2018/01,MALE,>= 40,متزوج,لا,>= 05,لا,< 5000,2018
3,4.0,الإحساء,إجتماعي,زواج,موظف حكومي,48000.0,< 1000,2018/01,MALE,>= 30,متزوج,لا,>= 02,لا,>= 5000,2018
4,5.0,الإحساء,مشروع,عربات البيع,NaN,150000.0,>= 1000,2018/01,MALE,>= 30,متزوج,لا,< 02,لا,< 5000,2018
5,6.0,الإحساء,إجتماعي,أسرة,موظف حكومي,36000.0,< 1000,2018/01,MALE,>= 30,متزوج,لا,>= 05,لا,>= 7500,2018
6,7.0,الإحساء,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2018/01,MALE,>= 30,متزوج,لا,>= 02,لا,>= 7500,2018
7,8.0,الإحساء,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,>= 5000,2018
8,9.0,الإحساء,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,< 5000,2018
9,10.0,الإحساء,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,>= 10000,2018
10,11.0,الإحساء,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,>= 5000,2018
11,12.0,الإحساء,إجتماعي,زواج,موظف قطاع خاص,54000.0,< 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,< 5000,2018
12,13.0,الإحساء,إجتماعي,زواج,موظف قطاع خاص,54000.0,< 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,>= 10000,2018
13,14.0,الإحساء,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2018/01,MALE,>= 30,متزوج,لا,>= 02,لا,>= 7500,2018
14,15.0,الإحساء,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,>= 5000,2018
15,16.0,الإحساء,إجتماعي,زواج,موظف حكومي,60000.0,>= 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,>= 7500,2018
16,17.0,الإحساء,إجتماعي,زواج,موظف قطاع خاص,54000.0,< 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,>= 10000,2018
17,18.0,الإحساء,إجتماعي,زواج,موظف قطاع خاص,54000.0,< 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,NaN,2018
18,19.0,الإحساء,إجتماعي,زواج,موظف قطاع خاص,60000.0,>= 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,>= 10000,2018
19,20.0,الإحساء,إجتماعي,زواج,موظف قطاع خاص,60000.0,>= 1000,2018/01,MALE,< 30,متزوج,لا,>= 02,لا,< 5000,2018

In [235]:
# data.to_csv(path+'gov_banking_data.csv')